apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cheeses
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: cheeses.minikube
    http:
      paths:
      - path: /stilton
        backend:
          service:
            name: stilton
            port:
              name: http
      - path: /cheddar
        backend:
          service:
            name: cheddar
            port:
              name: http
      - path: /wensleydale
        backend:
          service:
            name: wensleydale
            port:
              name: http
